.TH cb 1
.SH NAME
cb \- change the base of natural number

.SH SYNOPSIS
.B cb
[-i input_base]
[-o output_base]
number

.SH DESCRIPTION
.I cb
change the base of natural number. Althogh it is originally designed to deal with natural numbers, you can also use a negative number for input. Use -- characters before an input number so as to prevent the command from interpriting the number as an option.

.SH OPTIONS
Here is a summary of all the options.
.TP
.BI -i input_base
a base for interpriting an input number.
.TP
.BI -o output_base
a base for printing an output number.

.SH AUTHORS
Baba Tatsuya
