.TH gettmp 1
.SH NAME
gettmp \- get the path of tmp file.

.SH SYNOPSIS
.B gettmp
.I file_name

.SH DESCRIPTION
.I gettmp
searches the tmp file specified by \fIfile_name\fR in /var/tmp/mkexe and get the path of the file. The tmp file to search is usually created by mkexe command, but this command can work otherwise if the tmp file is correctly located.

.SH SEE ALSO
mkexe(1)

.SH AUTHORS
Baba Tatsuya
