.TH lbtex 1
.SH NAME
lbtex \- compile a tex file which has bibliography

.SH SYNOPSIS
.B lbtex
.I name

.SH DESCRIPTION
.I lbtex
make a .dvi file which contains bibliography.
.I name
is a body of a .tex file name; it is .tex file name without an extension. If you use .bib file, the file must exist in the same directory where you execute this command. When you have sample.tex file and samplebib.bib file in one directory, for example, you can use "lbtex sample" in the directory to get sample.dvi file, which contains bibliography.
.SH AUTHORS
Baba Tatsuya
