#!/bin/bash
while getopts i:o: OPT
do
    case $OPT in
        i) ibase=$OPTARG ;;
        o) obase=$OPTARG ;;
        \? ) exit 1 ;;
    esac
done

shift $(($OPTIND - 1))

if [ ! $ibase ]; then ibase=10; fi
if [ ! $obase ]; then obase=2; fi

echo "obase=$obase;ibase=$ibase;$1" | bc
