#!/bin/bash
while getopts i:o: OPT
do
    case $OPT in
        i) ibase=$OPTARG ;;
        o) obase=$OPTARG ;;
        \? ) exit 1 ;;
    esac
done

shift $(($OPTIND - 1))

number=$1

if [ ! $ibase ]; then
    base=$(basenum $number)
    number=$(stripbase $number)
    if [ $base -eq 0 ]; then ibase=10
    else ibase=$base; fi
fi

number=$(echo $number | tr '[:lower:]' '[:upper:]')

if [ ! $obase ]; then obase=2; fi

echo "obase=$obase;ibase=$ibase;$number" | bc
