#!/bin/bash
if [ $# -ne 1 ];then
    echo "gettmp: exactly 1 argument required" >&2
    echo "usage: gettmp file_name" >&2
    exit 1
fi
filename=$1
for dir in $TMP; do
    if [ -f "${dir}/${filename}" ]; then
        echo "${dir}/${filename}"
        exit 0
    fi
done
exit 1

